# Generated by Django 3.1.2 on 2020-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
