# Generated by Django 3.1.2 on 2020-10-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import playlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=playlist.models.upload_genre_location)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('artist', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=playlist.models.upload_song_location)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.song')),
            ],
        ),
    ]
