# Generated by Django 3.1.2 on 2020-10-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20201018_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=10),
        ),
    ]
